export const itemConstants = {
    GETALL_REQUEST: 'ITEM_GETALL_REQUEST',
    GETALL_SUCCESS: 'ITEM_GETALL_SUCCESS',
    GETALL_FAILURE: 'ITEM_GETALL_FAILURE',
    PUTTITLE_REQUEST: 'ITEM_PUTTITLE_REQUEST',
    PUTTITLE_SUCCESS: 'ITEM_PUTTITLE_SUCCESS',
    PUTTITLE_FAILURE: 'ITEM_PUTTITLE_FAILURE'
}